version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: names_db
    ports:
      - 3306:3306
    volumes:
      - ./words.txt:/var/lib/mysql-files/words.txt
      - ./lowcase.txt:/var/lib/mysql-files/lowcase.txt
      - ./schema:/docker-entrypoint-initdb.d